---
extends: stylelint-config-sass-guidelines
# For some editor plugins, which lint JS files (for CSS-in-JS, a pattern we
# don't use), and in VSCode at least, this results in nonsensical errors (in
# JS code)
ignoreFiles:
  - '**/*.js'
plugins:
  - stylelint-order
  - stylelint-prettier
  - stylelint-scss
rules:
  at-rule-empty-line-before:
    - always
    - except:
        - blockless-after-same-name-blockless
        - first-nested
      ignore:
        - after-comment
  block-no-empty: true
  color-hex-length: short
  color-no-invalid-hex: true
  comment-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - stylelint-commands
  comment-no-empty: true
  comment-whitespace-inside: always
  custom-property-empty-line-before:
    - always
    - except:
        - after-custom-property
        - first-nested
      ignore:
        - after-comment
        - inside-single-line-block
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-values
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-single-line-max-declarations: 1
  declaration-empty-line-before:
    - always
    - except:
        - after-declaration
        - first-nested
      ignore:
        - after-comment
        - inside-single-line-block
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-nesting-depth:
    - 4
    - ignore:
        - blockless-at-rules
  media-feature-name-no-unknown: true
  no-empty-source: true
  no-invalid-double-slash-comments: true
  order/order:
    - - custom-properties
      - dollar-variables
      - type: at-rule
        name: extend
      - type: at-rule
        name: include
        hasBlock: false
      - declarations
      - type: at-rule
        name: include
        hasBlock: true
      - rules
      - type: at-rule
        name: include
        parameter: breakpoint
        hasBlock: true
  prettier/prettier: true
  property-no-unknown: true
  rule-empty-line-before:
    - always-multi-line
    - except:
        - first-nested
        - after-single-line-comment
    - ignore:
        - after-comment
  scss/at-rule-no-unknown: true
  scss/dollar-variable-colon-space-after: null
  "@stylistic/function-parentheses-space-inside": null
  selector-class-pattern: '^[a-z][a-zA-Z0-9]+$'
  selector-max-compound-selectors: null
  selector-max-id: 2
  selector-no-qualifying-type:
    - true
    - ignore:
        - class
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  unit-no-unknown: true
