import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

const sourceSans = Inter({
  weight: ['200', '300', '400', '500', '700'],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>{children}</body>
    </html>
  );
}
